language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7-dev"
install:
    - pip install -r requirements.txt -r test_requirements.txt
script: ./runtests.sh
before_install:
  - "sudo mkdir -p /usr/include/postgresql/8.4/server"
#  - 'sudo apt-get -o Dpkg::Options::="--force-overwrite" install python-profiler'
before_script:
  - "psql -c 'create database webpy;' -U postgres"
  - mysql --user=root -e "create user 'scott'@'localhost' identified by 'tiger'; create database webpy; grant all privileges on webpy.* to 'scott'@'localhost' with grant option;"
notifications:
  irc: "irc.freenode.org#webpy"
